### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by alikoli** [adospace/rive-app#1]
It's not working on Windows. I'm getting: Non-negative number required. (Parameter 'width') .

 at Windows.Foundation.Size..ctor(Single width, Single height)
   at Windows.Foundation.Size..ctor(Double width, Double height)
   at Microsoft.Maui.Platform.LayoutPanel.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Measure(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.UIElement.Measure(Size availableSize)

**Comment by adospace** [comment]
which app is not working for you? any sample code?

**Comment by alikoli** [comment]
I tried to run rive-app on windows. There is no framework configuration for it so I added it:
  `  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>`
It seams there is some issue with scrollview.  I tried to run Test app from MauiReactor repo on Windows and it is working fine. Could you try to run RiveApp (this repo) on Windows?

**Comment by adospace** [comment]
Yes, RiveApp was built specifically for mobile platforms, Android and iOS, I don think it can work on Windows.

**Comment by alikoli** [comment]
What can I do to make it working, like, what are the main challenges?

**Comment by adospace** [comment]
Well, first I'm not sure how you can adapt that specific UI to a desktop window that is usually much wider but I would start commenting out components (for example the hamburger menu and the main page animation) and try to find the minimal version that at least starts.
